FROM ubuntu:16.04

RUN apt-get update
RUN apt-get -y upgrade

RUN apt-get install -y python-software-properties software-properties-common

RUN apt-get install -y locales

RUN locale-gen en_US.UTF-8
RUN export LANG=en_US.UTF-8

ENV INITRD=No TERM=dumb MY_TZ=America/Sao_Paulo
RUN rm /etc/timezone && echo $MY_TZ >> /etc/timezone

RUN LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php -y && \
  apt-get update

# Install apache, PHP, and supplimentary programs. curl and lynx-cur are for debugging the container.
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
  build-essential \
  imagemagick \
  ca-certificates \
  apache2 \
  libapache2-mod-php7.1 \
  php7.1 \
  php7.1-cli \
  php7.1-fpm \
  php7.1-dev \
  php7.1-bcmath \
  php7.1-bz2 \
  php7.1-mysql \
  php7.1-mbstring \
  php7.1-mcrypt \
  php7.1-gd \
  php-imagick \
  php7.1-curl \
  php7.1-intl \
  php7.1-common \
  php7.1-json \
  php7.1-opcache \
  php7.1-recode \
  php7.1-soap \
  php7.1-xml \
  php7.1-zip \
  php7.1-ldap \
  php7.1-opcache \
  php-interbase \
  php-apcu \
  php-pear \
  php-gettext \
  phpmyadmin \
  default-jre \
  libfbclient2 \
  git \
  rsyslog \
  curl \
  lynx-cur \
  wget \
  nano \
  vim

# Enable apache mods.
RUN a2enmod ssl
RUN a2enmod php7.1
RUN a2enmod rewrite

# Enable PHP Firebird mods.
RUN phpenmod pdo_firebird
RUN phpenmod interbase

RUN mkdir -p /etc/php/custom-conf.d

# Install Composer
RUN wget -c https://getcomposer.org/composer.phar && \
  chmod a+x composer.phar && \
  mv composer.phar /usr/bin/composer

# Manually set up the apache environment variables
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

WORKDIR /var/www/site/app

# Update the default apache site with the config we created.
COPY ./config/apache/httpd.conf /etc/apache2/sites-enabled/000-default.conf

RUN apt-get -y autoclean && apt-get -y autoremove && apt-get -y clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 80

ENV TERM=xterm

CMD apachectl stop

# By default, simply start apache.
CMD apache2ctl -D FOREGROUND
