FROM centos:7

RUN yum -y update && \
  yum install -y \
    java-1.8.0-openjdk \
    file \
    openssl-devel \
    initscripts \
    sudo

ENV PREFIX=/opt/firebird
ENV DBPATH=/databases

RUN bash -c "mkdir /databases"

COPY ./resources/firebird/2.5/scripts/install_fb25_hqbird_server_2018.sh .

RUN chmod a+x install_fb25_hqbird_server_2018.sh && \
  bash -c "./install_fb25_hqbird_server_2018.sh"

COPY ./resources/firebird/2.5/config/firebird/conf/firebird.conf ${PREFIX}
COPY ./resources/firebird/2.5/config/firebird/UDF ${PREFIX}/UDF

RUN bash -c "echo \"thread\" | ${PREFIX}/bin/changeMultiConnectMode.sh"

EXPOSE 3050/tcp
EXPOSE 8082/tcp
EXPOSE 8765/tcp

VOLUME ["/databases", "/opt/firebird"]

RUN yum clean all && \
  bash -c "rm -rf /var/cache/yum"

COPY /resources/firebird/2.5/config/hqbird/conf /opt/hqbird/conf
RUN chmod a+w /opt/hqbird/conf/access.properties

COPY ./resources/firebird/2.5/scripts/docker-entrypoint.sh .
RUN chmod 777 /docker-entrypoint.sh

COPY ./resources/firebird/2.5/run.sh .
RUN chmod a+x run.sh

ENTRYPOINT /docker-entrypoint.sh /run.sh
